# Generated by Django 5.0.4 on 2024-05-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_users", "0005_alter_ticket_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="description",
            field=models.TextField(blank=True, max_length=8192),
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="title",
            field=models.CharField(max_length=128),
        ),
    ]
