# Generated by Django 5.0.4 on 2024-05-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_users", "0006_alter_review_description_alter_review_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="body",
            field=models.TextField(blank=True, max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="headline",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
