# Generated by Django 5.0.4 on 2024-05-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_users", "0010_alter_ticket_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
