# Generated by Django 5.0.4 on 2024-04-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="mot_de_passe",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="nom_utilisateur",
            field=models.CharField(max_length=20),
        ),
    ]
